import os
from fpdf import FPDF, XPos, YPos
from fpdf.fonts import FontFace

class TaskPDFGenerator(FPDF):
    def __init__(self):
        super().__init__(orientation="P", unit="mm", format="a4")
        self.set_auto_page_break(auto=True, margin=20)
        # Set standard margins (15mm)
        self.set_margins(left=15, top=45, right=15) 
        self.add_page()

    def header(self):
        # --- Blue Banner Background ---
        # Temporarily remove margins to draw the banner edge-to-edge
        original_l_margin = self.l_margin
        self.set_left_margin(0)
        self.set_top_margin(0)
        
        # Main brand color
        self.set_fill_color(43, 119, 218) 
        # Draw rectangle (x, y, w, h) - Increased height for new text
        self.rect(0, 0, self.w, 40, 'F')

        # --- Banner Text ---
        self.set_xy(original_l_margin, 12)
        self.set_text_color(255, 255, 255) # White text
        
        # 1. Main Title (Big)
        self.set_font('Helvetica', 'B', 24)
        self.cell(0, 10, "Task Productivity Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
        
        # 2. Subtitle (Small, generated by...)
        self.set_font('Helvetica', '', 10)
        self.cell(0, 6, "Generated by Tivitapp", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='L')
        
        # 3. Date (Small)
        self.set_font('Helvetica', 'I', 10)
        self.cell(0, 6, "Date: January 20, 2026", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='L')

        # Restore margins for body content
        self.set_left_margin(original_l_margin)
        self.set_top_margin(45) # Push body content down below banner
        self.set_text_color(0, 0, 0)

        self.ln()

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', '', 9)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Tivitapp Productivity - Page {self.page_no()}', align='C')

    def _get_priority_icon(self, priority_text):
        path = "assets/"+priority_text+".png"
        return path if os.path.exists(path) else None

    def create_table(self, tasklist: dict):
        # --- Styles ---
        header_style = FontFace(emphasis="BOLD", color=(255, 255, 255), fill_color=(43, 119, 200))
        gray_row = FontFace(fill_color=(240, 240, 240))
        white_row = FontFace(fill_color=(255, 255, 255))

        self.set_font('Helvetica', '', 11)

        # --- Table Setup ---
        # Adjusted col_widths to sum roughly to 100% of usable width
        # Ratios: ID(8), Task(42), Deadline(20), Priority(15), State(15)
        with self.table(
            borders_layout="NONE", 
            col_widths=(8, 42, 20, 15, 5, 10), 
            width=self.epw, # Force table to use full Effective Page Width
            text_align=("C", "C", "C", "C", "L", "L"),
            line_height=1.5 * self.font_size
        ) as table:

            # --- Header Row ---
            row = table.row()
            headers = ["#", "Task", "Deadline", "Priority", "State"]
            for h in headers:
                if(h == "Priority"):
                    row.cell(h, style=header_style, align="C", colspan=2)
                else:
                    row.cell(h, style=header_style, align="C") # Center headers

            # --- Body Rows ---
            i = 1
            for taskid in tasklist:
                row = table.row()
                taskdetails = tasklist[taskid] 
                
                # Zebra striping
                current_style = gray_row if i % 2 == 0 else white_row
                
                # Cells
                row.cell(str(i), style=current_style)
                row.cell(str(taskdetails[0]), style=current_style) 
                row.cell(str(taskdetails[1]), style=current_style)

                # Priority with Icon
                priority_text = str(taskdetails[2])
                icon_path = self._get_priority_icon(priority_text)
                row.cell(priority_text, style=current_style)
                if icon_path:
                    row.cell(img=icon_path, img_fill_width=True, style=current_style)
                
                    

                row.cell(str(taskdetails[3]), style=current_style)
                
                i += 1
